### ISSUE TITLE
Suspicious code with string literal "TEST"

### ISSUE THREAD

**Issue by Leonetienne** [MrKinau/HSWormsCorona#5]
I'm not familiar with kotlin, but a friend of mine made me aware of a supsicious line in _app/src/main/java/de/hsworms/hs_wormszutritt/adapter/RoomAdapter.kt_ Line 29.

`RoomRegistration.checkIn(room.text.toString(), "TEST", activity)`

Could it be possible that this would just submit the matriculation number "TEST" to the server, regardless of what is set in the user prefs?

If i would be more proficient with kotlin i would check this myself, but i am not qualified. If this issue is bs, just close it.

**Comment by MrKinau** [comment]
Thanks for your issue,

I'll take a look. I'll Keep you updated in this issue.

**Comment by MrKinau** [comment]
Indeed,

this matrikelnummer has been used for testing. Unfortunately it got pushed in the repo. Luckily at least the checkout works properly, so the contact tracing still is possible (although it's harder, because only the checkout time is given). I'll check if this incedent also affects the uploaded releases.

**Comment by MrKinau** [comment]
Thanks to your friend. I've fixed this in 1.0.2.

I'll try to contact everyone using the current versions.
